# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 34a798bea8daffc295b7291908e54332205643b81885ad0d55dcc633d4b7794caf96a0384a2cd4f672f40eec038a79b418d8d324af4936641b52438e8d095177

test:
  secret_key_base: 9116d766fe7753ef561397ad520e48a5c5fb45b4a7312ac2f6b05a5eccd8f512db93bda09831d89962832acef0f0703682aa8b5e101a977efe06e34791de6f4f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
